module.exports = [
    "Abhayarishta", "Ahiphenasava", "Amritarishta", "Arvindasava", "Ashokarishta",
    "Ashwagandharishta", "Ayaskriti", "Balarishta", "Chandanasava", "Dantadyarishta",
    "Dashmoolarishta", "Devadarvarishta", "Draksharishta", "Drakshasava", "Jeerkadyarishta",
    "Kanakasava", "Karpurasava", "Khadirarishta", "Kumaryasava (A)", "Kumaryasava (B)",
    "Kutajarishta", "Lohasava", "Madhukasava", "Mridvikarishta", "Mustakarishta",
    "Parthadyarishta", "Pippaladyarishta", "Punarnavasava", "Rodhrasava", "Rohitakarishta",
    "Saraswatarishta", "Sharivadyasava", "Shrikhandasava", "Usheerasava", "Vasakasava",
    "Vidangarishta", "Ajmodark", "Arka Pudina", "Jatamansyarka", "Karpuradyarka",
    "Shatpushparka", "Agastya haritaki Rasayan", "Bhallatkadi Modak", "Bhargi Gud",
    "Bilvadi Leha", "Brahm Rasayan", "Chitrak Haritaki", "Chyavanprash", "Danti Haritaki",
    "Dashmool Haritaki", "Drakshavaleha", "Eladya Modak", "Gud Pippali", "Haridrakhand",
    "Haridavavirechan Leha", "Jeerakadi Modak", "Kalyanka Gud", "Kantakaryavaleha",
    "Kooshmandak Rasayan", "Kutajavaleha", "Laghuchinchadik Leha", "Madhusnuhi Rasayan",
    "Manibhadra Yog", "Mridvikadi Leha", "Narikehkhand", "Pugakhand", "Saubhagya Shunthi",
    "Shatavari Gud", "Shiv Gutika", "Suranavaleha", "Vasavaleha", "Amritottara",
    "Aragwadhadi", "Ardhavilva", "Ashtavarga", "Baljeerakadi", "Bharangyadi",
    "Brahat Manjisthadi", "Chaturbhadra", "Chhinnobhavadi", "Dashmoola", "Dashmoola Panchkoladi",
    "Dashmoolkatutraya", "Dasnagaradi", "Drakshadi", "Gandharva Hastadi", "Gijihvadi",
    "Mustakaranjadi", "Nayopayam", "Nimbadi", "Nyagrodhyadi", "Panchvalkal", "Panchnamrita",
    "Panchtikta", "Pashanbhedi", "Patoladi", "Patolmooladi", "Phaltrikadi", "Punarnavadi",
    "Punarnvashtak", "Rasanadi", "Rasanadi (Maha)", "Rasanerandadi", "Rasnasaptak",
    "Saptsara", "Shadanga", "Triyantyadi", "Trinpanchmoola", "Vasaguduchyadi", "Vidaryadi",
    "Varunadi Kwath Churna", "Amrita", "Amrita Bhallat Leha", "Amritaprash", "Ashoka",
    "Bastyamayantak", "Bazrak", "Traikantak", "Br. Phal", "Brahmi", "Chagladya", "Changeri",
    "Dadhik", "Dadimadi", "Dashmool", "Dhanvantar", "Dhatryadi", "Eladi", "Indukant",
    "Jatyadi", "Jeevantyadi", "Kalyanak", "Kasisadi", "Lasunadi", "Mahachetas", "Mahatriphaladya",
    "Mahapanchagabya", "Manhshiladi", "Mishrak Sneh", "Naresingh", "Nirgundi", "Panchagabya",
    "Panchatikta", "Panchatikta Guggulu", "Phalghrit", "Pipplyadi", "Sarswat", "Shatpal",
    "Sukumar", "Triphala", "Vyoshadi", "Yograj",
    "Ashwagandha Churna", "Brahmi Vati", "Chandraprabha Vati", "Chandrakala Ras", "Dashanga Lepa",
    "Dhatupaushtik Churna", "Divya Medha Vati", "Ekangveer Ras", "Gokshuradi Guggulu",
    "Guggulutiktakam Kwath", "Hingwashtak Churna", "Jatyadi Taila", "Kaishore Guggulu",
    "Kanchanar Guggulu", "Kamdudha Ras", "Kasturi Bhairav Ras", "Kumkumadi Taila",
    "Laxmivilas Ras", "Mahamanjishthadi Kwath", "Mahasudarshan Churna", "Manjistha Churna",
    "Medohar Vati", "Mukta Pishti", "Navayas Lauh", "Panchasakar Churna", "Pipplayasava",
    "Praval Pishti", "Pushyanug Churna", "Ras Sindoor", "Saptamrit Lauh", "Shankh Bhasma",
    "Shatavari Kalpa", "Shilajit Rasayan Vati", "Shodhit Gandhak", "Shwas Kuthar Ras",
    "Siddha Makardhwaj", "Sitopaladi Churna", "Sootshekhar Ras", "Sukshma Triphala",
    "Talisadi Churna", "Trikatu Churna", "Triphala Ghrita", "Triphala Rasayan",
    "Trivrit Lehyam", "Tapyadi Lauh", "Vasant Kusumakar Ras", "Vatakulantak Ras",
    "Vidang Churna", "Yogendra Ras"
  ];